
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Gaby
    url: jdbc:postgresql://localhost:5432/back_1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp: 
        use_jdbc_metadata_defaults: false
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
   
url-feign: http://localhost:8080/api

